### ISSUE TITLE
DateFormat crash, unsupported locale

### ISSUE THREAD

**Issue by Henrik-glt** [dart-lang/i18n#88]

**Comment by deakjahn** [comment]
The [docs](https://docs.flutter.dev/development/accessibility-and-localization/internationalization#adding-support-for-a-new-language) mentioned by OP do call `initializeDateFormattingCustom()` (at least in their current form). Still, calling `DateFormat` with the newly added locale still results in a crash. Does this mean that we still need to rely on this workaround?

**Comment by deakjahn** [comment]
Basically, what I found was that, unlike languages that are supported by `intl` itself, there seems to be an initialization issue. With intrinsic languages, one can ask for a different locale's `DateFormat` without issues: an app in a French locale can ask for a German date format, for instance. With custom added languages, this doesn't seem to work automatically, the custom localization delegate's `load()` is only called if the app itself runs in that locale, it throws otherwise.

Is this expected behavior or something that can be helped?
